on: [push, pull_request, workflow_dispatch]

name: Build Firmware

jobs:
  build-qmk:
    runs-on: ubuntu-latest

    steps:
      shell: bash
      - uses: actions/checkout@v4
      - uses: someposer/build-qmk-fw@v1
        with:
          keyboard: planck/rev7
          keymap: someposer
          local-keymap-path: planck/rev7/keymaps/someposer
      - uses: actions/upload-artifact@v4
        with:
          name: built-images
          path: qmk-output
