on: [push, pull_request, workflow_dispatch]

name: Build Firmware

jobs:
  build-qmk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: echo "GITHUB_SHA_SHORT=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - run: echo OPT_DEFS += -DCOMMIT_SHA=$GITHUB_SHA_SHORT >> planck/rev7/keymaps/someposer/rules.mk
      - uses: d3adb5/build-qmk-fw@v1
        with:
          keyboard: planck/rev7
          keymap: someposer
          local-keymap-path: planck/rev7/keymaps/someposer
      - uses: actions/upload-artifact@v4
        with:
          name: built-images-${{ env.GITHUB_SHA_SHORT }}
          path: qmk-output
          if-no-files-found: error
